/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/predatorMountText2.glb --transform 
Files: ./public/models/predatorMountText2.glb [251.37KB] > D:\_ProgrammingProjects\R3F\PredatorMounts\predatorMountText2-transformed.glb [13.69KB] (95%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/predatorMountText2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.predatorP.geometry} material={materials['SVGMat.001']} position={[-6.525, 0.952, -2.194]} scale={242.545} />
    </group>
  )
}

useGLTF.preload('/predatorMountText2-transformed.glb')
